version: '3.1'

services:
  postgis:
    image: postgis/postgis
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - .:/data

  cadastre:
    build:
      context: .
    restart: always
    ports:
      - 4567:4567
